---

extends:
  - airbnb

parser: babel-eslint

env:
  browser: true
  node: true

settings:
  import/resolver:
    webpack:
      config: 'webpack.config.js'

rules:
  import/extensions: 0
  react/jsx-filename-extension: 0
  arrow-body-style: 0
  react/jsx-props-no-spreading: 0
